CREATE TABLE users (
id SERIAL PRIMARY KEY,
	name VARCHAR(15) UNIQUE NOT NULL,
	email TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	"createAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE sessions(
    id SERIAL PRIMARY KEY,
	"userId" INTEGER REFERENCES users(id)  NOT NULL,
	token TEXT NOT NULL ,
	"createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE urls(
id SERIAL PRIMARY KEY,
	"userId" INTEGER REFERENCES users(id) NOT NULL,
	"url" TEXT UNIQUE NOT NULL,
	"shortenUrl" TEXT NOT NULL,
	"visitCount" INTEGER DEFAULT 0,
	"createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);




